# kubectl apply -f secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: melissa
type: Opaque
data:
  DATABASE_URL: cjJkYmM6cG9zdGdyZXNxbDovL2VwLWRyeS1mZWF0aGVyLWE1MDQ2NGppLnVzLWVhc3QtMi5hd3MubmVvbi50ZWNoOjU0MzIvam9zZT9zc2xtb2RlPXJlcXVpcmU=   # en Base64
  DATABASE_USERNAME: SkctQ2hhdEJvdF9vd25lcg==   # en Base64
  DATABASE_PASSWORD: UWJyNFlzVWZkejZS   # en Base64
  API_KEY: YmE4NjUzYWJjMm1zaGQ4Y2VkMWZjYmZlM2I2ZHAxYWM4ZTZqc24yZjg3ZGRlN2NhN2I=  # en Base64
  #DATABASE_URL: ${DATABASE_URL}   # en Base64
  #DATABASE_USERNAME: ${DATABASE_USERNAME}   # en Base64
  #DATABASE_PASSWORD: ${DATABASE_PASSWORD}   # en Base64
  #API_KEY: ${API_KEY}   # en Base64

#echo -n "demo123" | base64
#echo "ZGVtbzEyMw==" | base64 --decode