# 4kubectl apply -f secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: melissa
type: Opaque
data:
  DATABASE_URL: cjJkYmM6cG9zdGdyZXNxbDovL2VwLXNxdWFyZS13aWxkZmxvd2VyLWE1bWJhN2poLnVzLWVhc3QtMi5hd3MubmVvbi50ZWNoL25lb25kYj9zc2xtb2RlPXJlcXVpcmU=   # en Base64
  DATABASE_USERNAME: bmVvbmRiX293bmVy   # en Base64
  DATABASE_PASSWORD: b0hKalBTYjJGV0Qx   # en Base64
  API_KEY: QUl6YVN5RE8wNXNrSGNza3k2ZnlLWk1jUW9IXzQwLXJtRVg5VHBF  # en Base64
  API_BACKEND: aHR0cHM6Ly9mdXp6eS10cmFpbi00amdycXF2NHc3eHYzNWpyOS04MDg1LmFwcC5naXRodWIuZGV2L2FwaS9xdWVyaWVzL2FjdGl2ZQ==
  #DATABASE_URL: ${DATABASE_URL}   # en Base64
  #DATABASE_USERNAME: ${DATABASE_USERNAME}   # en Base64
  #DATABASE_PASSWORD: ${DATABASE_PASSWORD}   # en Base64
  #API_KEY: ${API_KEY}   # en Base64

#echo -n "demo123" | base64
#echo "ZGVtbzEyMw==" | base64 --decode